// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class ChangeLog
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject changeLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.ChangeLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectedDepartment("SelectedDepartment"),
		ChangeLog_Employee("TestSuite.ChangeLog_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChangeLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.ChangeLog"));
	}

	protected ChangeLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject changeLogMendixObject)
	{
		if (changeLogMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.ChangeLog", changeLogMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.ChangeLog");

		this.changeLogMendixObject = changeLogMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ChangeLog.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testsuite.proxies.ChangeLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.ChangeLog.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.ChangeLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.ChangeLog(context, mendixObject);
	}

	public static testsuite.proxies.ChangeLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.ChangeLog.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.ChangeLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.ChangeLog> result = new java.util.ArrayList<testsuite.proxies.ChangeLog>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.ChangeLog" + xpathConstraint))
			result.add(testsuite.proxies.ChangeLog.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SelectedDepartment
	 */
	public final String getSelectedDepartment()
	{
		return getSelectedDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedDepartment
	 */
	public final String getSelectedDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SelectedDepartment.toString());
	}

	/**
	 * Set value of SelectedDepartment
	 * @param selecteddepartment
	 */
	public final void setSelectedDepartment(String selecteddepartment)
	{
		setSelectedDepartment(getContext(), selecteddepartment);
	}

	/**
	 * Set value of SelectedDepartment
	 * @param context
	 * @param selecteddepartment
	 */
	public final void setSelectedDepartment(com.mendix.systemwideinterfaces.core.IContext context, String selecteddepartment)
	{
		getMendixObject().setValue(context, MemberNames.SelectedDepartment.toString(), selecteddepartment);
	}

	/**
	 * @return value of ChangeLog_Employee
	 */
	public final testsuite.proxies.Employee getChangeLog_Employee() throws com.mendix.core.CoreException
	{
		return getChangeLog_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeLog_Employee
	 */
	public final testsuite.proxies.Employee getChangeLog_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsuite.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChangeLog_Employee.toString());
		if (identifier != null)
			result = testsuite.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ChangeLog_Employee
	 * @param changelog_employee
	 */
	public final void setChangeLog_Employee(testsuite.proxies.Employee changelog_employee)
	{
		setChangeLog_Employee(getContext(), changelog_employee);
	}

	/**
	 * Set value of ChangeLog_Employee
	 * @param context
	 * @param changelog_employee
	 */
	public final void setChangeLog_Employee(com.mendix.systemwideinterfaces.core.IContext context, testsuite.proxies.Employee changelog_employee)
	{
		if (changelog_employee == null)
			getMendixObject().setValue(context, MemberNames.ChangeLog_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ChangeLog_Employee.toString(), changelog_employee.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return changeLogMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.ChangeLog that = (testsuite.proxies.ChangeLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.ChangeLog";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
