// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public enum Level
{
	Junior(new String[][] { new String[] { "en_US", "Junior" } }),
	Medior(new String[][] { new String[] { "en_US", "Medior" } }),
	Senior(new String[][] { new String[] { "en_US", "Senior" } });

	private java.util.Map<String,String> captions;

	private Level(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
